services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: udomi
      POSTGRES_PASSWORD: udomi_password
      POSTGRES_DB: udomi_me
    ports:
      - "5433:5432"
    volumes:
      - udomi_postgres_data:/var/lib/postgresql/data

volumes:
  udomi_postgres_data:
